CREATE TABLE TABLE_CUSTOMER (ID INT PRIMARY ,
                            FIRST_NAME VARCHAR(255),
                            LAST_NAME VARCHAR(255),
                            CREATE_DATE TIMESTAMP ,
                            UPDATE_DATE TIMESTAMP )
INSERT INTO TABLE_CUSTOMER VALUES (100, 'SURINDER', 'SINGH', SYSDATE,SYSDATE)
INSERT INTO TABLE_CUSTOMER VALUES (101, 'SHUBHAM', 'HIRPARA', SYSDATE,SYSDATE)